### ISSUE TITLE
Exceptions in the `make dev` log: warning or issue?

### ISSUE THREAD

**Issue by PieBru** [nilsherzig/LLocalSearch#10]
Hi Nils,

The `make dev` log raises some exceptions, the first one is:
```log
...
frontend-dev-1  |   VITE v5.1.6  ready in 1088 ms
frontend-dev-1  | 
frontend-dev-1  |   ➜  Local:   http://localhost:5173/
frontend-dev-1  |   ➜  Network: http://172.21.0.5:5173/
searxng         | 2024-04-01 16:35:12,806 ERROR:searx.engines.wikidata: Fail to initialize
searxng         | Traceback (most recent call last):
searxng         |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
searxng         |     return future.result(timeout)
searxng         |            ^^^^^^^^^^^^^^^^^^^^^^
searxng         |   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 458, in result
searxng         |     raise TimeoutError()
searxng         | TimeoutError
...
```

and this is the last one:
```log
searxng         | TimeoutError
searxng         | 
searxng         | The above exception was the direct cause of the following exception:
searxng         | 
searxng         | Traceback (most recent call last):
searxng         |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
searxng         |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng         |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng         |     guest_client_id = get_client_id()
searxng         |                       ^^^^^^^^^^^^^^^
searxng         |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 57, in get_client_id
searxng         |     resp = http_get(app_js_url)
searxng         |            ^^^^^^^^^^^^^^^^^^^^
searxng         |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
searxng         |     return request('get', url, **kwargs)
searxng         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng         |   File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
searxng         |     raise httpx.TimeoutException('Timeout', request=None) from e
searxng         | httpx.TimeoutException: Timeout
frontend-dev-1  | 
frontend-dev-1  |   VITE v5.1.6  ready in 1120 ms
frontend-dev-1  | 
frontend-dev-1  |   ➜  Local:   http://localhost:5173/
frontend-dev-1  |   ➜  Network: http://172.21.0.5:5173/
```

Should be considered warnings or is there any underlying issue?

**Comment by nilsherzig** [comment]
I general errors from everything that isn't "*-dev" / my code can be ignored. SearXNG is sometimes rate limited or just blocked by some of its providers, that's usually not a problem because it uses more than one. 

The only real problem / exception that I know of is #13
